services:
  db:
    image: postgres:16
    env_file:
      - ./env/.env
    ports:
      - "5433:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  backend:
    image: python:3.12-slim
    working_dir: /app
    env_file:
      - ./env/.env
    volumes:
      - ../backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      bash -lc "
      pip install -U pip &&
      pip install -e . &&
      alembic upgrade head &&
      PYTHONPATH=/app/src uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
      "

  frontend-build:
    image: node:18-alpine
    working_dir: /frontend
    volumes:
      - ../frontend:/frontend
      - frontend_build:/frontend/result_build
    command: >
      sh -lc "
      npm install --legacy-peer-deps &&
      rm -rf /tmp/frontend-build &&
      mkdir -p /tmp/frontend-build &&
      BUILD_PATH=/tmp/frontend-build npm run build &&
      mkdir -p /frontend/result_build &&
      find /frontend/result_build -mindepth 1 -maxdepth 1 -exec rm -rf {} + &&
      cp -r /tmp/frontend-build/* /frontend/result_build/ &&
      ls -lah /frontend/result_build
      "
    restart: "no"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - backend
      - frontend-build
    ports:
      - "8080:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ../backend/media:/media:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pg_data_dev:
  frontend_build: